import { ChevronDown, Download } from "lucide-react";
import { useState } from "react";

export function MatchScore({ report, analysis }) {
  const unavailable = analysis.status === "insufficient_data" || !analysis.requiredSkillCount;
  return <section className="score-panel"><p className="eyebrow">Overall match</p><div className="score-value">{unavailable ? "—" : `${report.matchScore}%`}</div><p>{unavailable ? "Requirements could not be extracted from this job description." : `${analysis.matchedSkillCount || 0} of ${analysis.requiredSkillCount} core requirements were found in your profile.`}</p></section>;
}
export function SkillAnalysis({ analysis, gaps }) { return <section className="report-section"><header><div><p className="eyebrow">Evidence-based comparison</p><h2>Skills and gaps</h2></div></header><div className="skills-grid"><div><h3>Verified strengths</h3>{(analysis.verifiedStrengths || analysis.matchedSkills || []).length ? <div className="tags">{(analysis.verifiedStrengths || analysis.matchedSkills).map((s) => <span key={s} className="tag tag-positive">{s}</span>)}</div> : <p className="muted">No direct strengths were identified.</p>}</div><div><h3>Gaps to address</h3>{gaps.length ? <div className="gap-list">{gaps.map((gap, i) => <article key={`${gap.skill}-${i}`}><div><strong>{gap.skill}</strong>{gap.category && <span>{gap.category}</span>}</div><b className={`priority priority-${gap.severity}`}>{gap.severity} priority</b>{gap.reason && <p>{gap.reason}</p>}</article>)}</div> : <p className="muted">No skills gaps were identified for this report.</p>}</div></div></section>; }
function Question({ question, index, type, onAssess }) { const [open, setOpen] = useState(false); const [practice, setPractice] = useState(false); const [answer, setAnswer] = useState(""); const [assessment, setAssessment] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submit = async () => { if (!answer.trim()) return setError("Write an answer before requesting feedback."); setBusy(true); setError(""); try { setAssessment(await onAssess({ questionIndex: index, questionText: question.question, userAnswer: answer.trim(), questionType: type })); } catch (err) { setError(err.response?.data?.message || "We could not evaluate that answer. Please try again."); } finally { setBusy(false); } }; return <article className="question"><button className="question-trigger" onClick={() => setOpen(!open)} aria-expanded={open}><span className="question-number">{String(index + 1).padStart(2, "0")}</span><span>{question.question}</span><ChevronDown size={18}/></button>{open && <div className="question-detail">{question.reason && <p><strong>Why it matters:</strong> {question.reason}</p>}{question.intention && <p><strong>Interviewer intent:</strong> {question.intention}</p>}{question.answer && <p><strong>Reference answer:</strong> {question.answer}</p>}{question.expectedTopics?.length > 0 && <p><strong>Key concepts:</strong> {question.expectedTopics.join(", ")}</p>}{question.starTips?.length > 0 && <p><strong>STAR tips:</strong> {question.starTips.join(" · ")}</p>}<button className="text-button" onClick={() => setPractice(!practice)}>{practice ? "Close practice" : "Practice your answer"}</button>{practice && <div className="practice"><label htmlFor={`answer-${type}-${index}`}>Your answer</label><textarea id={`answer-${type}-${index}`} value={answer} onChange={(e) => setAnswer(e.target.value)} rows="5" placeholder="Draft the answer you would give in an interview." />{error && <p className="field-error">{error}</p>}<button className="button button-primary" disabled={busy} onClick={submit}>{busy ? "Evaluating…" : "Get feedback"}</button>{assessment && <div className="assessment"><strong>Assessment: {assessment.score}/10</strong>{assessment.strengths?.length > 0 && <p><b>Strengths:</b> {assessment.strengths.join(" · ")}</p>}{assessment.improvementSuggestions?.length > 0 && <p><b>Improve:</b> {assessment.improvementSuggestions.join(" · ")}</p>}{assessment.betterAnswer && <p><b>Refined answer:</b> {assessment.betterAnswer}</p>}</div>}</div>}</div>}</article>; }
export function Questions({ title, questions = [], type, onAssess }) { return <section className="report-section"><header><div><p className="eyebrow">Practice set</p><h2>{title}</h2></div><span className="count">{questions.length}</span></header>{questions.length ? <div className="question-list">{questions.map((q, i) => <Question key={`${q.question}-${i}`} question={q} index={i} type={type} onAssess={onAssess}/>)}</div> : <p className="muted">No questions were generated in this category.</p>}</section>; }
export function Roadmap({ items = [] }) { return <section className="report-section"><header><div><p className="eyebrow">Preparation plan</p><h2>Roadmap</h2></div></header>{items.length ? <ol className="roadmap">{items.map((item, i) => <li key={`${item.day}-${i}`}><span>Day {item.day}</span><div><h3>{item.focus}</h3>{item.reason && <p>{item.reason}</p>}<ul>{item.tasks?.map((task) => <li key={task}>{task}</li>)}</ul></div><b className={`priority priority-${item.priority}`}>{item.priority}</b></li>)}</ol> : <p className="muted">No preparation roadmap was generated.</p>}</section>; }
export function ResumeDownload({ busy, onDownload }) { return <button className="button button-secondary" disabled={busy} onClick={onDownload}>{busy ? "Preparing PDF…" : <><Download size={17}/> Download tailored resume</>}</button>; }
