import { ArrowRight, FileText, Plus } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router";
import AppShell from "../components/layout/AppShell";
import { EmptyState, ErrorState, LoadingState } from "../components/ui/States";
import { interviewService } from "../services/interviewService";
import { useAuth } from "../features/auth/hooks/useAuth";
const date = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "—";
export default function Dashboard() { const { user } = useAuth(); const [reports, setReports] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = useCallback(() => { setLoading(true); setError(""); interviewService.list().then(setReports).catch((e) => setError(e.response?.data?.message || "We could not load your interview reports.")).finally(() => setLoading(false)); }, []); useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, [load]); return <AppShell><section className="page-intro"><p className="eyebrow">Interview preparation</p><h1>Welcome back{user?.username ? `, ${user.username}` : ""}.</h1><p>Compare your experience with a role, then practice against a targeted report.</p><Link className="button button-primary" to="/new-interview"><Plus size={17}/> Start a new interview</Link></section><section className="content-panel"><header className="section-heading"><div><h2>Recent reports</h2><p>Open a saved analysis or start a new one.</p></div><Link className="text-link" to="/history">View all <ArrowRight size={16}/></Link></header>{loading ? <LoadingState label="Loading reports…"/> : error ? <ErrorState message={error} onRetry={load}/> : reports.length ? <div className="report-table"><div className="report-row report-table-head"><span>Target role</span><span>Match</span><span>Created</span><span /></div>{reports.slice(0, 5).map((report) => <div className="report-row" key={report._id}><div><strong>{report.title || "Target role"}</strong><small>{report.skillGaps?.length ? `${report.skillGaps.length} skill gaps identified` : "Report available"}</small></div><span>{typeof report.matchScore === "number" ? `${report.matchScore}%` : "—"}</span><span>{date(report.createdAt)}</span><Link aria-label={`Open ${report.title || "report"}`} to={`/interview/${report._id}`}><FileText size={18}/></Link></div>)}</div> : <EmptyState title="No interview reports yet" message="Generate your first report to see your results here."/>}</section></AppShell>; }
